// AUTOGENERATED
import axios from 'axios';
import React, { useState, useEffect, useRef, useMemo, useCallback, type ComponentProps, type ReactNode } from "react";
import { useTranslation } from "react-i18next";
import AshokaChakra from "../../../assets/ashoka-chakra-png-46987.png";
import WebsiteLogo from "../../../assets/website-logo.png";
import { motion, AnimatePresence, useMotionValue, useReducedMotion, useInView } from "motion/react";
import { Link, useNavigate, useLocation, Outlet } from "react-router-dom";
import { Plus, Minus, ChevronDown, Globe, Tractor, Sprout, CloudSun, Leaf, ArrowRight, FileText, Fingerprint, CreditCard, ScrollText, Home, Baby, Building2, Users, Sparkles, Check, Search, BookOpen, CheckCircle, ShieldCheck, Lock, Share2, Link as LinkIcon, Landmark, MessageSquare, Briefcase, GraduationCap, FileCheck, Menu, X, FileSearch, Lightbulb, ChevronLeft, ChevronRight, Layers, Compass } from "lucide-react";
import * as NavigationMenuPrimitive from "@radix-ui/react-navigation-menu";
import { cva } from "class-variance-authority";
import clsx, { type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import { ChatBot } from "../../../features/chatbot/ChatBot";
import eduJobsImg from '../../../assets/edu-jobs.png';
import scholarshipImg from '../../../assets/scholarship.png';
import govServiceImg from '../../../assets/gov-service.jpg';
import schemeImg from '../../../assets/scheme.jpg';
import documentImg from '../../../assets/document.jpg';

import { cn } from "../../../lib/utils";

const documents = [
  { name: 'Aadhaar Card', icon: Fingerprint, path: '/services?search=aadhaar' },
  { name: 'PAN Card', icon: CreditCard, path: '/services?search=pan' },
  { name: 'Income Certificate', icon: ScrollText, path: '/services?search=income' },
  { name: 'Caste Certificate', icon: Users, path: '/services?search=caste' },
  { name: 'Residence / Domicile', icon: Home, path: '/services?search=domicile' },
  { name: 'Birth Certificate', icon: Baby, path: '/services?search=birth' },
  { name: 'Marriage Certificate', icon: Building2, path: '/services?search=marriage' },
  { name: 'Other Documents', icon: FileText, path: `/services?category=${encodeURIComponent('Documents & Certificates')}` },
];

// Reusing Users from lucide, importing above


export const DocumentServices = () => {
  return (
    <section className="py-20 md:py-28 bg-transparent">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

        <div className="flex flex-col md:flex-row items-start md:items-end justify-between mb-16 gap-6">
          <div className="max-w-2xl">
            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-100px" }}
              className="text-3xl md:text-4xl font-bold text-slate-900 tracking-tight mb-4"
            >
              Government Documents Made Simple
            </motion.h2>
            <motion.p
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-100px" }}
              transition={{ delay: 0.1 }}
              className="text-lg text-slate-600"
            >
              Understand what you need, where to apply, what documents are required, and what to do next.
            </motion.p>
          </div>

          <motion.div
            initial={{ opacity: 0, x: 20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ delay: 0.2 }}
          >
            <Link
              to={`/services?category=${encodeURIComponent('Documents & Certificates')}`}
              className="inline-flex items-center justify-center bg-white hover:bg-slate-50 text-slate-700 border border-slate-200 px-6 py-3 rounded-full font-semibold transition-all shadow-sm group whitespace-nowrap"
            >
              View All Documents <ArrowRight size={16} className="ml-2 group-hover:translate-x-1 transition-transform" />
            </Link>
          </motion.div>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-6">
          {documents.map((doc, index) => {
            const Icon = doc.icon;
            return (
              <motion.div
                key={doc.name}
                initial={{ opacity: 0, scale: 0.95 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.4, delay: index * 0.05 }}
              >
                <Link
                  to={doc.path}
                  className="group flex flex-col items-center text-center bg-slate-50 hover:bg-primary-50 border border-slate-100 hover:border-primary-200 p-6 md:p-8 rounded-2xl transition-all duration-300 hover:shadow-md"
                >
                  <div className="w-14 h-14 bg-white rounded-full flex items-center justify-center mb-4 text-primary-600 shadow-sm group-hover:scale-110 transition-transform duration-300">
                    <Icon size={24} strokeWidth={1.5} />
                  </div>
                  <h3 className="font-semibold text-slate-800 group-hover:text-primary-700 transition-colors text-sm md:text-base">
                    {doc.name}
                  </h3>
                </Link>
              </motion.div>
            );
          })}
        </div>

      </div>
    </section>
  );
};
