// AUTOGENERATED
import axios from 'axios';
import React, { useState, useEffect, useRef, useMemo, useCallback, type ComponentProps, type ReactNode } from "react";
import { useTranslation } from "react-i18next";
import AshokaChakra from "../../../assets/ashoka-chakra-png-46987.png";
import WebsiteLogo from "../../../assets/website-logo.png";
import { motion, AnimatePresence, useMotionValue, useReducedMotion, useInView } from "motion/react";
import { Link, useNavigate, useLocation, Outlet } from "react-router-dom";
import { Plus, Minus, ChevronDown, Globe, Tractor, Sprout, CloudSun, Leaf, ArrowRight, FileText, Fingerprint, CreditCard, ScrollText, Home, Baby, Building2, Users, Sparkles, Check, Search, BookOpen, CheckCircle, ShieldCheck, Lock, Share2, Link as LinkIcon, Landmark, MessageSquare, Briefcase, GraduationCap, FileCheck, Menu, X, FileSearch, Lightbulb, ChevronLeft, ChevronRight, Layers, Compass } from "lucide-react";
import * as NavigationMenuPrimitive from "@radix-ui/react-navigation-menu";
import { cva } from "class-variance-authority";
import clsx, { type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import { ChatBot } from "../../../features/chatbot/ChatBot";
import eduJobsImg from '../../../assets/edu-jobs.png';
import scholarshipImg from '../../../assets/scholarship.png';
import govServiceImg from '../../../assets/gov-service.jpg';
import schemeImg from '../../../assets/scheme.jpg';
import documentImg from '../../../assets/document.jpg';

import { cn } from "../../../lib/utils";


    const AnimatedCounter = ({ end, duration = 2 }: { end: number, duration?: number }) => {
      const [count, setCount] = useState(0);
      const ref = useRef(null);
      const isInView = useInView(ref, { once: true, margin: "-50px" });

      useEffect(() => {
        if (isInView) {
          let startTimestamp: number | null = null;
          const step = (timestamp: number) => {
            if (!startTimestamp) startTimestamp = timestamp;
            const progress = Math.min((timestamp - startTimestamp) / (duration * 1000), 1);

            // Easing function (easeOutExpo)
            const easeProgress = progress === 1 ? 1 : 1 - Math.pow(2, -10 * progress);

            setCount(Math.floor(easeProgress * end));

            if (progress < 1) {
              window.requestAnimationFrame(step);
            }
          };
          window.requestAnimationFrame(step);
        }
      }, [end, duration, isInView]);

      return <span ref={ref}>{count}</span>;
    };

    export const PlatformStats = () => {
      const stats = [
    { label: 'Government Schemes', value: 1453, suffix: '' },
    { label: 'Government Jobs & Exams', value: 401, suffix: '' },
    { label: 'Scholarships & Education', value: 1110, suffix: '' },
    { label: 'Documents & Certificates', value: 58, suffix: '' },
    { label: 'Agriculture Services', value: 862, suffix: '' },
  ];

      return (
        <section className="py-16 md:py-24 bg-transparent border-t border-slate-100/50">
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-primary-50/50 via-white to-white pointer-events-none" />

          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-8 lg:gap-6 divide-x divide-transparent lg:divide-slate-200">

              {stats.map((stat, index) => (
                <motion.div
                  key={stat.label}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-50px" }}
                  transition={{ duration: 0.5, delay: index * 0.1 }}
                  className="flex flex-col items-center justify-center text-center px-2 lg:px-4"
                >
                  <div className="text-3xl lg:text-4xl xl:text-5xl font-extrabold text-slate-900 mb-2 tabular-nums tracking-tighter">
                    <AnimatedCounter end={stat.value} />
                    <span className="text-primary-500">{stat.suffix}</span>
                  </div>
                  <div className="text-[11px] sm:text-xs md:text-sm font-bold text-slate-500 uppercase tracking-wider">
                    {stat.label}
                  </div>
                </motion.div>
              ))}

            </div>
          </div>
        </section>
      );
    };             
