// AUTOGENERATED
import axios from 'axios';
import React, { useState, useEffect, useRef, useMemo, useCallback, type ComponentProps, type ReactNode } from "react";
import { useTranslation } from "react-i18next";
import AshokaChakra from "../../../assets/ashoka-chakra-png-46987.png";
import WebsiteLogo from "../../../assets/website-logo.png";
import { motion, AnimatePresence, useMotionValue, useReducedMotion, useInView } from "motion/react";
import { Link, useNavigate, useLocation, Outlet } from "react-router-dom";
import { Plus, Minus, ChevronDown, Globe, Tractor, Sprout, CloudSun, Leaf, ArrowRight, FileText, Fingerprint, CreditCard, ScrollText, Home, Baby, Building2, Users, Sparkles, Check, Search, BookOpen, CheckCircle, ShieldCheck, Lock, Share2, Link as LinkIcon, Landmark, MessageSquare, Briefcase, GraduationCap, FileCheck, Menu, X, FileSearch, Lightbulb, ChevronLeft, ChevronRight, Layers, Compass } from "lucide-react";
import * as NavigationMenuPrimitive from "@radix-ui/react-navigation-menu";
import { cva } from "class-variance-authority";
import clsx, { type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import { ChatBot } from "../../../features/chatbot/ChatBot";
import eduJobsImg from '../../../assets/edu-jobs.png';
import scholarshipImg from '../../../assets/scholarship.png';
import govServiceImg from '../../../assets/gov-service.jpg';
import schemeImg from '../../../assets/scheme.jpg';
import documentImg from '../../../assets/document.jpg';

import { cn } from "../../../lib/utils";

const trustPillars = [
  {
    title: 'Bank-Grade Security',
    description: 'Our platform uses standard 256-bit encryption to ensure your browsing and any interactions are completely secure.',
    icon: Lock,
  },
  {
    title: 'Zero Data Sharing',
    description: 'We do not sell, share, or monetize your personal data. Your searches and profile information remain strictly private.',
    icon: Share2,
  },
  {
    title: 'Official Links Only',
    description: 'We never host application forms. Every service strictly redirects to verified .gov.in or .nic.in official portals.',
    icon: LinkIcon,
  }
];

export const TrustSection = () => {
  return (
    <section className="py-24 md:py-32 bg-slate-900 relative overflow-hidden">
      {/* Background gradients */}
      <div className="absolute top-0 left-0 w-full h-full bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-primary-900/40 via-slate-900 to-slate-900 pointer-events-none" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">

        <div className="text-center mb-16 md:mb-20">
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true, margin: "-100px" }}
            className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-primary-900/50 text-primary-400 mb-6 border border-primary-700/50 shadow-inner"
          >
            <ShieldCheck size={32} />
          </motion.div>
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ delay: 0.1 }}
            className="text-4xl md:text-5xl font-extrabold text-white tracking-tight mb-6"
          >
            Your Trust, Our Priority
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ delay: 0.2 }}
            className="text-lg md:text-xl text-slate-400 max-w-2xl mx-auto font-medium"
          >
            We are an <span className="font-bold text-white">independent guidance platform</span>. We are <span className="text-rose-400 font-bold underline decoration-rose-900/50 underline-offset-4">not</span> affiliated with the Government of India, but we prioritize your safety above all.
          </motion.p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {trustPillars.map((pillar, index) => {
            const Icon = pillar.icon;
            return (
              <motion.div
                key={pillar.title}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.5, delay: 0.2 + (index * 0.1) }}
                className="bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-3xl p-8 flex flex-col items-center text-center hover:border-primary-500/50 transition-colors"
              >
                <div className="w-14 h-14 rounded-2xl bg-slate-700/50 text-primary-400 flex items-center justify-center mb-6">
                  <Icon size={28} strokeWidth={2} />
                </div>
                <h3 className="text-xl font-bold text-white mb-3">
                  {pillar.title}
                </h3>
                <p className="text-slate-400 leading-relaxed">
                  {pillar.description}
                </p>
              </motion.div>
            );
          })}
        </div>

      </div>
    </section>
  );
};
