// AUTOGENERATED
import axios from 'axios';
import React, { useState, useEffect, useRef, useMemo, useCallback, type ComponentProps, type ReactNode } from "react";
import { useTranslation } from "react-i18next";
import AshokaChakra from "../../../assets/ashoka-chakra-png-46987.png";
import WebsiteLogo from "../../../assets/website-logo.png";
import { motion, AnimatePresence, useMotionValue, useReducedMotion, useInView } from "motion/react";
import { Link, useNavigate, useLocation, Outlet } from "react-router-dom";
import { Plus, Minus, ChevronDown, Globe, Tractor, Sprout, CloudSun, Leaf, ArrowRight, FileText, Fingerprint, CreditCard, ScrollText, Home, Baby, Building2, Users, Sparkles, Check, Search, BookOpen, CheckCircle, ShieldCheck, Lock, Share2, Link as LinkIcon, Landmark, MessageSquare, Briefcase, GraduationCap, FileCheck, Menu, X, FileSearch, Lightbulb, ChevronLeft, ChevronRight, Layers, Compass } from "lucide-react";
import * as NavigationMenuPrimitive from "@radix-ui/react-navigation-menu";
import { cva } from "class-variance-authority";
import clsx, { type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import { ChatBot } from "../../../features/chatbot/ChatBot";
import eduJobsImg from '../../../assets/edu-jobs.png';
import scholarshipImg from '../../../assets/scholarship.png';
import govServiceImg from '../../../assets/gov-service.jpg';
import schemeImg from '../../../assets/scheme.jpg';
import documentImg from '../../../assets/document.jpg';

import { cn } from "../../../lib/utils";

const benefits = [
  {
    title: 'One Place',
    description: 'Find multiple citizen services from one platform instead of searching across dozens of different websites.',
    icon: Layers,
    color: 'text-orange-600',
    bgColor: 'bg-orange-50',
  },
  {
    title: 'Simple Language',
    description: 'Complex government information translated and explained in an easy-to-understand way.',
    icon: MessageSquare,
    color: 'text-blue-600',
    bgColor: 'bg-blue-50',
  },
  {
    title: 'Clear Guidance',
    description: 'Understand eligibility, required documents, application process, and exactly what to do next.',
    icon: Compass,
    color: 'text-primary-600',
    bgColor: 'bg-primary-50',
  },
  {
    title: 'Official Sources',
    description: 'We always provide direct links to authoritative government sources for verification and safe application.',
    icon: ShieldCheck,
    color: 'text-purple-600',
    bgColor: 'bg-purple-50',
  },
  {
    title: 'Citizen Focused',
    description: 'Designed specifically for students, job seekers, farmers, families, and everyday citizens.',
    icon: Users,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-50',
  },
  {
    title: 'No Unnecessary Complexity',
    description: 'Simple navigation, clear actions, and no overwhelming forms or confusing terminology.',
    icon: Sparkles,
    color: 'text-rose-600',
    bgColor: 'bg-rose-50',
  }
];

export const WhyOneGuide = () => {
  return (
    <section className="py-20 md:py-28 bg-transparent border-t border-slate-100/50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

        <div className="text-center mb-16 md:mb-20">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            className="text-3xl md:text-4xl font-bold text-slate-900 tracking-tight"
          >
            Why OneGuide?
          </motion.h2>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-10">
          {benefits.map((benefit, index) => {
            const Icon = benefit.icon;
            return (
              <motion.div
                key={benefit.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                className="flex flex-col md:flex-row gap-6 items-start"
              >
                <div className={`shrink-0 w-12 h-12 rounded-full ${benefit.bgColor} ${benefit.color} flex items-center justify-center`}>
                  <Icon size={24} strokeWidth={1.5} />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-slate-900 mb-2">
                    {benefit.title}
                  </h3>
                  <p className="text-slate-600 text-sm leading-relaxed">
                    {benefit.description}
                  </p>
                </div>
              </motion.div>
            );
          })}
        </div>

      </div>
    </section>
  );
};
