// AUTOGENERATED
import axios from 'axios';
import React, { useState, useEffect, useRef, useMemo, useCallback, type ComponentProps, type ReactNode } from "react";
import { useTranslation } from "react-i18next";
import AshokaChakra from "../../assets/ashoka-chakra-png-46987.png";
import WebsiteLogo from "../../assets/website-logo.png";
import { motion, AnimatePresence, useMotionValue, useReducedMotion, useInView } from "motion/react";
import { Link, useNavigate, useLocation, Outlet } from "react-router-dom";
import { Plus, Minus, ChevronDown, Globe, Tractor, Sprout, CloudSun, Leaf, ArrowRight, FileText, Fingerprint, CreditCard, ScrollText, Home, Baby, Building2, Users, Sparkles, Check, Search, BookOpen, CheckCircle, ShieldCheck, Lock, Share2, Link as LinkIcon, Landmark, MessageSquare, Briefcase, GraduationCap, FileCheck, Menu, X, FileSearch, Lightbulb, ChevronLeft, ChevronRight, Layers, Compass } from "lucide-react";
import * as NavigationMenuPrimitive from "@radix-ui/react-navigation-menu";
import { cva } from "class-variance-authority";
import clsx, { type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import { ChatBot } from "../../features/chatbot/ChatBot";
import eduJobsImg from '../../assets/edu-jobs.png';
import scholarshipImg from '../../assets/scholarship.png';
import govServiceImg from '../../assets/gov-service.jpg';
import schemeImg from '../../assets/scheme.jpg';
import documentImg from '../../assets/document.jpg';

import { cn } from "../../lib/utils";

// Widget 1: Live Statistics (Large number, mini line chart)
export const LiveStatisticsWidget = () => {
  const [value, setValue] = useState(12847);

  useEffect(() => {
    const interval = setInterval(() => {
      // Fluctuate organically by a small random amount
      setValue(prev => prev + Math.floor(Math.random() * 15) - 5);
    }, 2500);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="w-full flex flex-col items-center justify-center relative p-2 h-32">
      {/* Live Indicator */}
      <div className="absolute top-0 right-2 flex items-center gap-1.5 bg-green-50 px-2 py-1 rounded-full border border-green-100">
        <div className="w-1.5 h-1.5 bg-green-500 rounded-full animate-ping absolute" />
        <div className="w-1.5 h-1.5 bg-green-500 rounded-full relative" />
        <span className="text-[10px] font-bold text-green-700 uppercase tracking-wider">Live</span>
      </div>

      <div className="text-4xl font-extrabold text-gray-900 tracking-tighter tabular-nums transition-all duration-500">
        {value.toLocaleString()}
      </div>
      <div className="flex items-center gap-2 mt-1">
        <span className="text-sm font-semibold text-primary-600 bg-primary-50 px-1.5 py-0.5 rounded text-[11px]">+8.4%</span>
        <span className="text-xs font-medium text-gray-400">vs last hour</span>
      </div>

      {/* Mini Line Chart */}
      <div className="mt-4 w-24 h-6 opacity-40">
        <svg viewBox="0 0 100 30" className="w-full h-full overflow-visible">
          <path
            d="M 0 25 C 20 25, 20 5, 40 15 C 60 25, 60 5, 80 10 C 90 12, 95 0, 100 5"
            fill="none"
            stroke="currentColor"
            strokeWidth="3"
            className="text-blue-500 transition-all duration-1000 ease-in-out drop-shadow-sm"
            strokeLinecap="round"
          />
        </svg>
      </div>
    </div>
  );
};


// Widget 2: Activity Progress (Circular ring)
export const ActivityProgressWidget = () => {
  const [progress, setProgress] = useState(78);

  useEffect(() => {
    const interval = setInterval(() => {
      setProgress(prev => {
        const next = prev + (Math.random() > 0.5 ? 2 : -1);
        return Math.min(Math.max(next, 60), 95); // Keep between 60 and 95
      });
    }, 3000);
    return () => clearInterval(interval);
  }, []);

  const circumference = 2 * Math.PI * 40;
  const strokeDashoffset = circumference - (progress / 100) * circumference;

  return (
    <div className="w-full flex flex-col items-center justify-center relative h-32">
      <div className="relative w-24 h-24 flex items-center justify-center">
        {/* Background Track */}
        <svg className="w-full h-full transform -rotate-90" viewBox="0 0 100 100">
          <circle cx="50" cy="50" r="40" fill="none" stroke="#f3f4f6" strokeWidth="8" />
          {/* Animated Progress */}
          <circle
            cx="50" cy="50" r="40"
            fill="none"
            stroke="currentColor"
            strokeWidth="8"
            strokeLinecap="round"
            className="text-blue-500 transition-all duration-1000 ease-out drop-shadow-sm"
            strokeDasharray={circumference}
            strokeDashoffset={strokeDashoffset}
          />
        </svg>
        <div className="absolute inset-0 flex flex-col items-center justify-center">
          <span className="text-xl font-bold text-gray-900 tabular-nums">{progress}%</span>
        </div>
      </div>
      <div className="mt-3 flex items-center gap-1.5">
        <div className="w-1.5 h-1.5 bg-blue-500 rounded-full animate-pulse" />
        <span className="text-xs font-semibold text-blue-600 uppercase tracking-wider">Processing</span>
      </div>
    </div>
  );
};


// Widget 3: Real-Time Activity (Waveform bars)
export const RealTimeActivityWidget = () => {
  const [users, setUsers] = useState(2481);
  const [bars, setBars] = useState<number[]>(Array(12).fill(10));

  useEffect(() => {
    const interval = setInterval(() => {
      setUsers(prev => prev + Math.floor(Math.random() * 7) - 3);
      setBars(prev => prev.map(() => 10 + Math.random() * 20));
    }, 1500);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="w-full flex flex-col items-center justify-center h-32">
      <div className="text-3xl font-extrabold text-gray-900 tabular-nums mb-1 transition-all duration-300">
        {users.toLocaleString()}
      </div>
      <div className="text-xs font-medium text-gray-400 mb-6 uppercase tracking-widest">
        Active Users
      </div>

      {/* Waveform */}
      <div className="flex items-end gap-1.5 h-12">
        {bars.map((height, i) => (
          <div
            key={i}
            className="w-1.5 bg-blue-400 rounded-t-sm transition-all duration-500 ease-in-out opacity-80 shadow-[0_0_8px_rgba(59,130,246,0.3)]"
            style={{ height: `${height}px` }}
          />
        ))}
      </div>
    </div>
  );
};


// Widget 4: Growth Performance (Animated bar chart)
export const GrowthPerformanceWidget = () => {
  const [data, setData] = useState([30, 45, 25, 60, 40, 75, 50]);

  useEffect(() => {
    const interval = setInterval(() => {
      setData(prev => {
        const newData = [...prev.slice(1), 30 + Math.random() * 50];
        return newData;
      });
    }, 2000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="w-full flex flex-col items-center justify-center relative h-32 px-4">
      <div className="w-full flex justify-between items-end mb-4 px-2">
        <div className="flex flex-col items-start">
          <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Weekly Growth</span>
          <span className="text-sm font-semibold text-primary-600 bg-primary-50 px-2 py-0.5 rounded-full shadow-sm border border-primary-100">+24.6%</span>
        </div>
        <div className="text-2xl font-bold text-gray-900 tabular-nums">
          8,492
        </div>
      </div>

      {/* Bar Chart */}
      <div className="flex items-end gap-2 h-16 w-full px-2">
        {data.map((val, i) => {
          const isLatest = i === data.length - 1;
          return (
            <div key={i} className="flex-1 flex flex-col items-center justify-end h-full relative group">
              <div
                className={`w-full rounded-t-md transition-all duration-700 ease-in-out ${isLatest ? 'bg-blue-500 shadow-[0_0_12px_rgba(59,130,246,0.4)]' : 'bg-gray-200'}`}
                style={{ height: `${val}%` }}
              />
            </div>
          );
        })}
      </div>
    </div>
  );
};
