// AUTOGENERATED
import axios from 'axios';
import React, { useState, useEffect, useRef, useMemo, useCallback, type ComponentProps, type ReactNode } from "react";
import { useTranslation } from "react-i18next";
import AshokaChakra from "../../assets/ashoka-chakra-png-46987.png";
import WebsiteLogo from "../../assets/website-logo.png";
import { motion, AnimatePresence, useMotionValue, useReducedMotion, useInView } from "motion/react";
import { Link, useNavigate, useLocation, Outlet } from "react-router-dom";
import { Plus, Minus, ChevronDown, Globe, Tractor, Sprout, CloudSun, Leaf, ArrowRight, FileText, Fingerprint, CreditCard, ScrollText, Home, Baby, Building2, Users, Sparkles, Check, Search, BookOpen, CheckCircle, ShieldCheck, Lock, Share2, Link as LinkIcon, Landmark, MessageSquare, Briefcase, GraduationCap, FileCheck, Menu, X, FileSearch, Lightbulb, ChevronLeft, ChevronRight, Layers, Compass } from "lucide-react";
import * as NavigationMenuPrimitive from "@radix-ui/react-navigation-menu";
import { cva } from "class-variance-authority";
import clsx, { type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import { ChatBot } from "../../features/chatbot/ChatBot";
import eduJobsImg from '../../assets/edu-jobs.png';
import scholarshipImg from '../../assets/scholarship.png';
import govServiceImg from '../../assets/gov-service.jpg';
import schemeImg from '../../assets/scheme.jpg';
import documentImg from '../../assets/document.jpg';

import { cn } from "../../lib/utils";

interface FeatureCardProps {
  icon?: React.ReactNode;
  title: string;
  description: string;
  action?: React.ReactNode;
  className?: string;
}

export function FeatureCard({ icon, title, description, action, className = '' }: FeatureCardProps) {
  return (
    <div className={`group bg-white/95 backdrop-blur-xl rounded-[12px] shadow-[0px_1px_2px_0px_rgba(0,0,0,0.25)] flex flex-col items-center text-center p-8 transition-all duration-500 hover:scale-[1.02] hover:shadow-[0_8px_30px_rgb(0,0,0,0.12)] hover:border-blue-100/50 relative overflow-hidden ${className}`}>

      {/* Subtle Inner Glow on Hover */}
      <div className="absolute inset-0 bg-gradient-to-b from-blue-50/0 to-blue-50/0 group-hover:from-blue-50/50 transition-colors duration-500 pointer-events-none" />
      {/* Top Icon/Illustration Slot */}
      {icon && (
        <div className="mb-8 flex justify-center w-full relative z-10">
          {icon}
        </div>
      )}

      {/* Title */}
      <h3 className="text-[20px] font-medium text-gray-900 mb-6 tracking-tight relative z-10 group-hover:text-blue-900 transition-colors duration-300">
        {title}
      </h3>

      {/* Signature Framer Gradient Separator Line */}
      <div className="w-full max-w-[158px] h-[2px] bg-gradient-to-r from-transparent via-[#E3E3E3] to-transparent mb-6" />

      {/* Description */}
      <p className="text-[#8C8C8C] text-[15px] leading-[1.6] mb-8 font-medium">
        {description}
      </p>

      {/* Action / Link (Optional) */}
      {action && (
        <div className="mt-auto">
          {action}
        </div>
      )}

    </div>
  );
}
